# Generated by Django 4.2.7 on 2023-11-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_number_numberdistribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familleEmp', models.CharField(db_index=True, max_length=20, null=True, verbose_name='Фамилия')),
                ('firstNameEmp', models.CharField(max_length=20, null=True, verbose_name='Имя')),
                ('lastNameEmp', models.CharField(max_length=20, null=True, verbose_name='Отчество')),
                ('cityEmp', models.CharField(max_length=20, null=True, verbose_name='Город проживания')),
                ('streetEmp', models.CharField(max_length=20, null=True, verbose_name='Улица')),
                ('homeEmp', models.IntegerField(default=0, verbose_name='номер дома')),
                ('apartmentEmp', models.IntegerField(default=0, verbose_name='Номер квартиры')),
                ('phone', models.CharField(default=0, max_length=11, verbose_name='Номер телефона')),
            ],
        ),
    ]
