# Generated by Django 4.2.7 on 2023-11-21 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employees', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.employees', verbose_name='Код сотрудника')),
                ('number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.number', verbose_name='Номер гостиницы')),
            ],
        ),
        migrations.CreateModel(
            name='DutySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayStartWork', models.DateField(null=True, verbose_name='Время начала работы')),
                ('dayEndWork', models.DateField(null=True, verbose_name='Время окончания работы')),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel.employees', verbose_name='Код сотрудника')),
            ],
        ),
    ]
