# Generated by Django 4.2.7 on 2023-11-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_rename_client_id_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='file',
            field=models.FileField(null=True, upload_to='uploads_model'),
        ),
    ]
