# Generated by Django 4.2.7 on 2023-11-22 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_roomservice_work_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DutySchedule',
        ),
    ]
