# Generated by Django 4.2.7 on 2023-11-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_alter_employees_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='file',
        ),
        migrations.AddField(
            model_name='employees',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y%m%d/', verbose_name='Фото'),
        ),
    ]
